<rb-tab
	#<%=id%>="tab"
	[id]="'<%=id%>'"
	[label]="'<%=config.label%>'"
	style="<%=config.inlineStyle%>"
	[active]="<%=parents.tabsection%>.isTabVisible(<%=id%>)"
	[hidden]="!<%=id%>.active"
	(register)="<%=parents.tabsection%>.register(<%=id%>)">
	#content#
</rb-tab>
