<rb-tab
	#<%=id%>="tab"
	[id]="'<%=id%>'"
	[label]="'<%=config.getString('label')%>'"
	style="<%=config.getString('inlineStyle')%>"
	[active]="<%=tabsection%>.isTabVisible(<%=id%>)"
	[hidden]="!<%=id%>.active"
	(register)="<%=tabsection%>.register(<%=id%>)">
	#content#
</rb-tab>
